
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.evilcraft]
		enable_compat_evilcraft = true

	[Compatibility.consecration]
		enable_compat_consecration = true

